version: "3"

volumes:
  db_data:
  upload_data:

networks:
  web:
  db:

services:
  # ************************************************************* #
  # Api
  # ************************************************************* #
  qualidade-backend:
    image: python:3-alpine
    container_name: qualidade-backend
    working_dir: /backend
    networks:
      - web
      - db

    volumes:
      - ./backend:/backend
      # - /backend/node_modules
    ports: #TODO: remover ao incluir o reverse
      - 5000:5000
    command: bash -c "python3 router.py"

  # ************************************************************* #
  # Servidor nginx
  # ************************************************************* #

  qualidade-frontend:
    image: nginx:1.17.10-alpine
    container_name: frontend-nginx
    networks:
      - web
    depends_on:
      - crescamais-backend
      # - crescamais-front-user
      - frontend
    volumes:
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    restart: always
